/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testeii.View;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import testeii.Controller.ContagemDeVotos;
import testeii.Model.Candidato;

/**
 *
 * @author antoniositoe
 */
public class ContagemPrincipal extends javax.swing.JFrame {

        ContagemDeVotos Contagem = new ContagemDeVotos();
        Candidato candidatoTemporario = null;
        String itemSelecionadoTemporario = null;

        public ContagemPrincipal() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                JTable = new javax.swing.JTable();
                jPanel3 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                Jname = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jLabel11 = new javax.swing.JLabel();
                Jrecenciados = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                Jmunicipio = new javax.swing.JLabel();
                jPanel6 = new javax.swing.JPanel();
                jLabel13 = new javax.swing.JLabel();
                Jbi = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                OpenTela = new javax.swing.JButton();
                BTNVotar = new javax.swing.JButton();
                JVotos = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                VotoNulo = new javax.swing.JButton();

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                JTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Nome", "BI", "votos", "Municipio"
                                }));
                JTable.setName(""); // NOI18N
                JTable.addMouseListener(new java.awt.event.MouseAdapter() {

                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                JTableMousePressed(evt);
                        }
                });
                JTable.addKeyListener(new java.awt.event.KeyAdapter() {

                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                JTableKeyReleased(evt);
                        }
                });

                jScrollPane1.setViewportView(JTable);

                jPanel3.setBackground(java.awt.Color.white);

                jLabel3.setText("Nome:");

                Jname.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
                Jname.setText("0");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(Jname,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                249,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(28, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(Jname,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                39,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(46, Short.MAX_VALUE)));

                jPanel4.setBackground(java.awt.Color.white);

                jLabel11.setText("Recenciados");

                Jrecenciados.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
                Jrecenciados.setText("0");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel11)
                                                                                .addComponent(Jrecenciados,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                122,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(39, Short.MAX_VALUE)));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Jrecenciados,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel5.setBackground(java.awt.Color.white);

                jLabel6.setText("Municipio:");

                Jmunicipio.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
                Jmunicipio.setText("?");

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(Jmunicipio,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                203,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Jmunicipio)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel6.setBackground(java.awt.Color.white);

                jLabel13.setText("BI");

                Jbi.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
                Jbi.setText("0");

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel13)
                                                                                .addComponent(Jbi,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                268,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jLabel13)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Jbi)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jLabel2.setText("ESCOLHA O SEU MUNICIPIO");

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Cidade de Maputo", "Matola", "Marracuene", "Manhiça", "Boane" }));
                jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox1ActionPerformed(evt);
                        }
                });

                OpenTela.setText("Cadastrar Candidato");
                OpenTela.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                OpenTelaActionPerformed(evt);
                        }
                });

                BTNVotar.setBackground(new java.awt.Color(70, 175, 161));
                BTNVotar.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
                BTNVotar.setForeground(java.awt.Color.white);
                BTNVotar.setText("Votar");
                BTNVotar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BTNVotarActionPerformed(evt);
                        }
                });

                JVotos.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
                JVotos.setText("0");

                jLabel1.setBackground(java.awt.Color.black);
                jLabel1.setFont(new java.awt.Font("Ubuntu Thin", 1, 24)); // NOI18N
                jLabel1.setText("SEJA BEM VINDO AS ELEICOES ");

                VotoNulo.setBackground(java.awt.Color.red);
                VotoNulo.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
                VotoNulo.setForeground(java.awt.Color.white);
                VotoNulo.setText("Votar Branco");
                VotoNulo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                VotoNuloActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(21, 21, 21)
                                                                                                .addComponent(jLabel1))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(54, 54, 54)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                1085,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jPanel3,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(jPanel4,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(12, 12, 12)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(JVotos,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                67,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                .addComponent(BTNVotar,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                202,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jPanel5,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                                .addComponent(jPanel6,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                244,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(VotoNulo,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                202,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(OpenTela,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                202,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addComponent(jComboBox1,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                235,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))))
                                                                .addContainerGap(43, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addComponent(jLabel1)
                                                                .addGap(13, 13, 13)
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(OpenTela,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                46,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jComboBox1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                46,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(VotoNulo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                45,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel6,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                12,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(BTNVotar,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                45,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JVotos))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                276,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(41, 41, 41)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void VotoNuloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VotoNuloActionPerformed
                // TODO add your handling code here:
                if (candidatoTemporario != null) {
                        var votos = Contagem.VotoNulo(candidatoTemporario);
                        JVotos.setText(Double.toString(votos));
                        if (itemSelecionadoTemporario != null) {
                                Contagem.atualizaJtable(JTable, itemSelecionadoTemporario);
                        }
                }
        }// GEN-LAST:event_VotoNuloActionPerformed

        private void OpenTelaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_OpenTelaActionPerformed
                // TODO add your handling code here:
                CadastroCandidatos novaTela = new CadastroCandidatos();
                novaTela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                novaTela.setVisible(true);
        }// GEN-LAST:event_OpenTelaActionPerformed

        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
                String itemSelecionado = (String) jComboBox1.getSelectedItem();
                itemSelecionadoTemporario = itemSelecionado;
                var novoArray = Contagem.filterCandidatos(itemSelecionado);

                DefaultTableModel model = (DefaultTableModel) JTable.getModel();

                if (novoArray != null) {
                        model.setNumRows(0);
                        novoArray.forEach(data -> {
                                model.addRow(new Object[] { data.getNome(), data.getBI(), data.getVotos(),
                                                data.municipio.getNome() });
                        });
                }
        }// GEN-LAST:event_jComboBox1ActionPerformed

        private void BTNVotarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTNVotarActionPerformed
                if (candidatoTemporario != null) {
                        var votos = Contagem.VotarUmCandidato(candidatoTemporario);
                        JVotos.setText(Double.toString(votos));
                        if (itemSelecionadoTemporario != null) {
                                Contagem.atualizaJtable(JTable, itemSelecionadoTemporario);
                        }
                }
        }

        private void JTableMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_JTableMousePressed
                // Obtém a linha e coluna clicada
                int row = JTable.rowAtPoint(evt.getPoint());

                String nome = JTable.getValueAt(row, 0).toString();
                var candidato = Contagem.mostrarOCandidato(nome);
                candidatoTemporario = candidato;
                Jname.setText(nome);
                Jmunicipio.setText(candidato.municipio.getNome());
                Jbi.setText(Double.toString(candidato.getBI()));
                JVotos.setText(Double.toString(candidato.getVotos()));
                Jrecenciados.setText(Double.toString(candidato.municipio.getQuantidadeDeRecenciado()));
        }// GEN-LAST:event_JTableMousePressed

        private void JTableKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_JTableKeyReleased
                // TODO add your handling code here:
                int row = JTable.getSelectedRow();

                String nome = JTable.getValueAt(row, 0).toString();
                var candidato = Contagem.mostrarOCandidato(nome);
                candidatoTemporario = candidato;

                Jname.setText(nome);
                Jmunicipio.setText(candidato.municipio.getNome());
                Jbi.setText(Double.toString(candidato.getBI()));
                JVotos.setText(Double.toString(candidato.getVotos()));
                Jrecenciados.setText(Double.toString(candidato.municipio.getQuantidadeDeRecenciado()));
        }// GEN-LAST:event_JTableKeyReleased

        public static void main(String args[]) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new ContagemPrincipal().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BTNVotar;
        private javax.swing.JTable JTable;
        private javax.swing.JLabel JVotos;
        private javax.swing.JLabel Jbi;
        private javax.swing.JLabel Jmunicipio;
        private javax.swing.JLabel Jname;
        private javax.swing.JLabel Jrecenciados;
        private javax.swing.JButton OpenTela;
        private javax.swing.JButton VotoNulo;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables
}
