/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package firstdesktopapp;

import firstdesktopapp.model.Pessoa;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author antoniositoe
 */
public class PessoaGUI extends javax.swing.JFrame {
    ArrayList<Pessoa> ListaDePessoas= new ArrayList<Pessoa>();
    
    ComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
   
    /**
     * Creates new form PessoaGUI
     */
    public PessoaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TxtNome = new javax.swing.JTextField();
        TxtIdade = new javax.swing.JTextField();
        ComboPai = new javax.swing.JComboBox<>();
        ComboMae = new javax.swing.JComboBox<>();
        AddPessoa = new javax.swing.JButton();
        ComboFilhos = new javax.swing.JComboBox<>();
        BtnRetornaFIlhos = new javax.swing.JButton();
        ComboAvos = new javax.swing.JComboBox<>();
        BtnRetornaAvos = new javax.swing.JButton();
        BtnMostraFamilia = new javax.swing.JButton();
        ComboGenero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(38, 38, 38));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel2.setText("Idade");

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel8.setText("Genero");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel3.setText("Pai");

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel4.setText("Mae");

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel5.setText("Mostra filhos");

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel6.setText("Mostra Avos Maternos");

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel7.setText("Mostrar familia");

        jSeparator1.setBackground(new java.awt.Color(8, 130, 247));
        jSeparator1.setForeground(new java.awt.Color(8, 130, 247));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setAutoscrolls(true);

        TxtNome.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 13)); // NOI18N

        TxtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdadeActionPerformed(evt);
            }
        });

        ComboPai.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        ComboPai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sempai" }));
        ComboPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPaiActionPerformed(evt);
            }
        });

        ComboMae.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        ComboMae.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SemMae" }));

        AddPessoa.setBackground(new java.awt.Color(8, 130, 247));
        AddPessoa.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 14)); // NOI18N
        AddPessoa.setForeground(new java.awt.Color(255, 255, 255));
        AddPessoa.setText("Adicionar Pessoa");
        AddPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Sans", 0, 13), new java.awt.Color(8, 130, 247))); // NOI18N
        AddPessoa.setBorderPainted(false);
        AddPessoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPessoaActionPerformed(evt);
            }
        });

        ComboFilhos.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        BtnRetornaFIlhos.setBackground(new java.awt.Color(8, 130, 247));
        BtnRetornaFIlhos.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 14)); // NOI18N
        BtnRetornaFIlhos.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetornaFIlhos.setText("Retorna Filhos");
        BtnRetornaFIlhos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetornaFIlhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornaFIlhosActionPerformed(evt);
            }
        });

        ComboAvos.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        BtnRetornaAvos.setBackground(new java.awt.Color(8, 130, 247));
        BtnRetornaAvos.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 14)); // NOI18N
        BtnRetornaAvos.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetornaAvos.setText("Retorna Avos Maternos");
        BtnRetornaAvos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetornaAvos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornaAvosActionPerformed(evt);
            }
        });

        BtnMostraFamilia.setBackground(new java.awt.Color(8, 130, 247));
        BtnMostraFamilia.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 14)); // NOI18N
        BtnMostraFamilia.setForeground(new java.awt.Color(255, 255, 255));
        BtnMostraFamilia.setText("Mostra familia");
        BtnMostraFamilia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMostraFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostraFamiliaActionPerformed(evt);
            }
        });

        ComboGenero.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        ComboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        ComboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtIdade)
                    .addComponent(ComboPai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboMae, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(TxtNome)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboAvos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRetornaAvos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRetornaFIlhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMostraFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRetornaFIlhos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboAvos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(BtnRetornaAvos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnMostraFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboPai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboMae, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AddPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdadeActionPerformed

    private void AddPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPessoaActionPerformed
        // TODO add your handling code here:
      var nome = TxtNome.getText();
      var idade =Integer.parseInt(TxtIdade.getText());
      
      String nomePai = (String) ComboPai.getSelectedItem();
      String nomeMae = (String) ComboMae.getSelectedItem();
      String genero = (String) ComboGenero.getSelectedItem();
      
      Pessoa pessoaQuePodeSerPai=null;
      Pessoa pessoaQuePodeSerMae=null;
     //      procurar dentro do array
      
      for(Pessoa apessoa: ListaDePessoas){
          if(apessoa.getNome().equals(nomePai)){
            pessoaQuePodeSerPai = apessoa;
          }
          if(apessoa.getNome().equals(nomeMae)){
            pessoaQuePodeSerMae = apessoa;
          }
       
      }
    
              
     Pessoa pessoa= new Pessoa(nome,idade, genero,pessoaQuePodeSerPai, pessoaQuePodeSerMae);
     ListaDePessoas.add(pessoa);

      
      if(genero.equals("M")){
         ComboPai.addItem(nome);
      } else {
         ComboMae.addItem(nome);
      }
      
      ComboAvos.addItem(nome);
      ComboFilhos.addItem(nome);
      TxtNome.setText("");
//      TxtIdade.setText("");
      
    }//GEN-LAST:event_AddPessoaActionPerformed

    private void BtnMostraFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostraFamiliaActionPerformed
        // TODO add your handling code here:
            // Cria a estrutura de dados hierárquica
     DefaultMutableTreeNode pessoaRaiz = new DefaultMutableTreeNode("Pessoas");
     
           // Preenchimento da árvore
        for (Pessoa pessoa:ListaDePessoas ) {
           if(!(pessoa.getPai() == null)) {
             DefaultMutableTreeNode parentNode = new DefaultMutableTreeNode(pessoa.getPai().getNome());
             var pai = pessoa.getPai().getNome();
             
             if(!this.hasNodeWithName(pessoaRaiz, pai)){
          
             for (Pessoa pessoa2:ListaDePessoas) {
                DefaultMutableTreeNode childNode = new DefaultMutableTreeNode(pessoa2.getNome());
                
                 if(!(pessoa2.getPai() == null)){
                   if(pessoa2.getPai().getNome().equals(pai) ){
		     parentNode.add(childNode);
	           }   
                 }
               }
              pessoaRaiz.add(parentNode);
              }
             }        
           }
        
              // Preenchimento da árvore
        for (Pessoa pessoa:ListaDePessoas ) {
           if(!(pessoa.getMae() == null)) {
             DefaultMutableTreeNode parentNode = new DefaultMutableTreeNode(pessoa.getMae().getNome());
             var mae = pessoa.getMae().getNome();
             
             if(!this.hasNodeWithName(pessoaRaiz, mae)){
          
             for (Pessoa pessoa2:ListaDePessoas) {
                DefaultMutableTreeNode childNode = new DefaultMutableTreeNode(pessoa2.getNome());
                
                 if(!(pessoa2.getMae() == null)){
                   if(pessoa2.getMae().getNome().equals(mae) ){
		     parentNode.add(childNode);
	           }   
                 }
               }
              pessoaRaiz.add(parentNode);
              }
             }        
           }
        
    // Cria o modelo de árvore
    DefaultTreeModel modelo = new DefaultTreeModel(pessoaRaiz);
    JTree tree = new JTree(modelo);

    // Adiciona o JTree em um contêiner
    JFrame frame = new JFrame("Exemplo JTree");
    frame.add(new JScrollPane(tree));
    frame.pack();
    frame.setVisible(true);
    }//GEN-LAST:event_BtnMostraFamiliaActionPerformed

    
   public boolean hasNodeWithName(DefaultMutableTreeNode root, String name) {
    if (root == null || name == null) {
        return false;
    }

    if (name.equals(root.toString())) {
        return true;
    }

    for (int i = 0; i < root.getChildCount(); i++) {
        DefaultMutableTreeNode child = (DefaultMutableTreeNode) root.getChildAt(i);
        boolean hasNode = hasNodeWithName(child, name);
        if (hasNode) {
            return true;
        }
    }

    return false;
  }
    
    private void BtnRetornaFIlhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornaFIlhosActionPerformed
        // TODO add your handling code here:
        String nome = (String) ComboFilhos.getSelectedItem();
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for(Pessoa pessoa:ListaDePessoas ){
		if(!(pessoa.getPai() == null)){
		   if(pessoa.getPai().getNome().equals(nome) ){
			 model.addElement(pessoa.getNome());
		      }
		  } 
                 if(!(pessoa.getMae()== null)){
		   if(pessoa.getMae().getNome().equals(nome) ){
			 model.addElement(pessoa.getNome());
		      }
		  } 
        }
    
        
        JList<String> itemList = new JList<>(model);
        
        JScrollPane scrollPane = new JScrollPane(itemList);
        JFrame frame = new JFrame("Exemplo de JList");
        frame.add(scrollPane);
        frame.setSize(300, 200);
        frame.setVisible(true);
    }//GEN-LAST:event_BtnRetornaFIlhosActionPerformed

    private void BtnRetornaAvosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornaAvosActionPerformed
        // TODO add your handling code here:
        String nome = (String) ComboAvos.getSelectedItem();  
        
        DefaultListModel<String> model = new DefaultListModel<>();
        
        for(Pessoa pessoa:ListaDePessoas ){
         if(pessoa.getNome().equals(nome)){
	   if(!(pessoa.getMae() == null)){
	     if(!(pessoa.getMae().getPai() == null)){
                 model.addElement(pessoa.getMae().getPai().getNome());
	      }
	      if(!(pessoa.getMae().getMae() == null)){
                 model.addElement(pessoa.getMae().getMae().getNome());
	       }
              }
             }
           }
         
        JList<String> itemList = new JList<>(model);
        
        JScrollPane scrollPane = new JScrollPane(itemList);
        JFrame frame = new JFrame("Exemplo de JList");
        frame.add(scrollPane);
        frame.setSize(300, 200);
        frame.setVisible(true);
    }//GEN-LAST:event_BtnRetornaAvosActionPerformed

    private void ComboPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPaiActionPerformed

    private void ComboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPessoa;
    private javax.swing.JButton BtnMostraFamilia;
    private javax.swing.JButton BtnRetornaAvos;
    private javax.swing.JButton BtnRetornaFIlhos;
    private javax.swing.JComboBox<String> ComboAvos;
    private javax.swing.JComboBox<String> ComboFilhos;
    private javax.swing.JComboBox<String> ComboGenero;
    private javax.swing.JComboBox<String> ComboMae;
    private javax.swing.JComboBox<String> ComboPai;
    private javax.swing.JTextField TxtIdade;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
