/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package firstdesktopapp;

import firstdesktopapp.model.Pessoa;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author antoniositoe
 */
public class PessoaGUI extends javax.swing.JFrame {
    ArrayList<Pessoa> ListaDePessoas= new ArrayList<Pessoa>();
    
    ComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
   
    /**
     * Creates new form PessoaGUI
     */
    public PessoaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtIdade = new javax.swing.JTextField();
        ComboPai = new javax.swing.JComboBox<>();
        ComboMae = new javax.swing.JComboBox<>();
        AddPessoa = new javax.swing.JButton();
        ComboFilhos = new javax.swing.JComboBox<>();
        BtnRetornaFIlhos = new javax.swing.JButton();
        ComboAvos = new javax.swing.JComboBox<>();
        BtnRetornaAvos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(38, 38, 38));

        jLabel1.setText("Nome");

        jLabel2.setText("Idade");

        jLabel3.setText("Pai");

        jLabel4.setText("Mae");

        jLabel5.setText("Mostra filhos");

        jLabel6.setText("Mostra Avos Maternos");

        TxtNome.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 13)); // NOI18N

        TxtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdadeActionPerformed(evt);
            }
        });

        ComboPai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecionar" }));
        ComboPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPaiActionPerformed(evt);
            }
        });

        ComboMae.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecionar" }));

        AddPessoa.setForeground(new java.awt.Color(0, 0, 1));
        AddPessoa.setText("Adicionar Pessoa");
        AddPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Sans", 0, 13), new java.awt.Color(8, 130, 247))); // NOI18N
        AddPessoa.setBorderPainted(false);
        AddPessoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPessoaActionPerformed(evt);
            }
        });

        ComboFilhos.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        ComboFilhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboFilhosActionPerformed(evt);
            }
        });

        BtnRetornaFIlhos.setForeground(new java.awt.Color(0, 0, 1));
        BtnRetornaFIlhos.setText("Retorna Filhos");
        BtnRetornaFIlhos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetornaFIlhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornaFIlhosActionPerformed(evt);
            }
        });

        ComboAvos.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        BtnRetornaAvos.setForeground(new java.awt.Color(0, 0, 1));
        BtnRetornaAvos.setText("Retorna Avos Maternos");
        BtnRetornaAvos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetornaAvos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornaAvosActionPerformed(evt);
            }
        });

        ListArea.setColumns(20);
        ListArea.setRows(5);
        jScrollPane1.setViewportView(ListArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboMae, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboPai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtIdade)
                    .addComponent(TxtNome)
                    .addComponent(AddPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnRetornaFIlhos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboAvos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnRetornaAvos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRetornaFIlhos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComboAvos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRetornaAvos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboPai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboMae, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdadeActionPerformed

    private void AddPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPessoaActionPerformed
        // TODO add your handling code here:
      var nome = TxtNome.getText();
      var idade =Integer.parseInt(TxtIdade.getText());
      
      String nomePai = (String) ComboPai.getSelectedItem();
      String nomeMae = (String) ComboMae.getSelectedItem();
      
      
      Pessoa pessoaQuePodeSerPai=null;
      Pessoa pessoaQuePodeSerMae=null;
     //      procurar dentro do array
      
      for(Pessoa apessoa: ListaDePessoas){
          if(apessoa.getNome().equals(nomePai)){
            pessoaQuePodeSerPai = apessoa;
          }
          if(apessoa.getNome().equals(nomeMae)){
            pessoaQuePodeSerMae = apessoa;
          }
       
      }
    
              
     Pessoa pessoa= new Pessoa(nome,idade, pessoaQuePodeSerPai, pessoaQuePodeSerMae);
     ListaDePessoas.add(pessoa);

      
   
       ComboMae.addItem(nome);
       ComboPai.addItem(nome);
      ComboAvos.addItem(nome);
      ComboFilhos.addItem(nome);
      TxtNome.setText("");
      TxtIdade.setText("");
      
    }//GEN-LAST:event_AddPessoaActionPerformed

    
   public boolean hasNodeWithName(DefaultMutableTreeNode root, String name) {
    if (root == null || name == null) {
        return false;
    }

    if (name.equals(root.toString())) {
        return true;
    }

    for (int i = 0; i < root.getChildCount(); i++) {
        DefaultMutableTreeNode child = (DefaultMutableTreeNode) root.getChildAt(i);
        boolean hasNode = hasNodeWithName(child, name);
        if (hasNode) {
            return true;
        }
    }

    return false;
  }
    
    private void BtnRetornaFIlhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornaFIlhosActionPerformed
        // TODO add your handling code here:
        String nome = (String) ComboFilhos.getSelectedItem();
        
//        DefaultListModel<String> model = new DefaultListModel<>();
        for(Pessoa pessoa:ListaDePessoas ){
		if(!(pessoa.getPai() == null)){
		   if(pessoa.getPai().getNome().equals(nome) ){
			ListArea.append(pessoa.getNome()+"\n");
		      }
		  } 
                 if(!(pessoa.getMae()== null)){
		   if(pessoa.getMae().getNome().equals(nome) ){
			 
                         ListArea.append(pessoa.getNome()+"\n");
		      }
		  } 
        }

    }//GEN-LAST:event_BtnRetornaFIlhosActionPerformed

    private void BtnRetornaAvosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornaAvosActionPerformed
        // TODO add your handling code here:
        String nome = (String) ComboAvos.getSelectedItem();  
        
      ListArea.setText("");
        
        for(Pessoa pessoa:ListaDePessoas ){
         if(pessoa.getNome().equals(nome)){
	   if(!(pessoa.getMae() == null)){
	     if(!(pessoa.getMae().getPai() == null)){
                   ListArea.append(pessoa.getMae().getPai().getNome()+"\n");
                 
	      }
	      if(!(pessoa.getMae().getMae() == null)){
                    ListArea.append(pessoa.getMae().getMae().getNome()+"\n");
	       }
              }
             }
           }
         
      
    }//GEN-LAST:event_BtnRetornaAvosActionPerformed

    private void ComboPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPaiActionPerformed

    private void ComboFilhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboFilhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboFilhosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPessoa;
    private javax.swing.JButton BtnRetornaAvos;
    private javax.swing.JButton BtnRetornaFIlhos;
    private javax.swing.JComboBox<String> ComboAvos;
    private javax.swing.JComboBox<String> ComboFilhos;
    private javax.swing.JComboBox<String> ComboMae;
    private javax.swing.JComboBox<String> ComboPai;
    private javax.swing.JTextArea ListArea;
    private javax.swing.JTextField TxtIdade;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
